name: NeoSky
main: me.neoblade298.neosky.NeoSky
authors: [Ascheladd, FoPzl, ShanaChan]
depend: [NeoCore, WorldEdit]
softdepend: []
version: 0.1
api-version: 1.20
commands:
   island:
      aliases: [is]
      description: NeoSky Island command
   neosky:
      aliases: [ns]
      description: NeoSky General command
   neoskyadmin:
      aliases: [nsa]
      description: NeoSky Admin command